# docker-compose.yml
version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app

    # Используем сетевой режим host: контейнер разделяет сеть с хостом
    network_mode: host

    # Переменные окружения (Mongo ищется на localhost:27017)
    environment:
      DB_NAME: "namaz_db"
      # MONGO_URI по умолчанию уже 'mongodb://localhost:27017/'
      # Но на всякий случай можно явно:
      MONGO_URI: "mongodb://localhost:27017/"

    # Автоматический рестарт
    restart: unless-stopped

    # Команда запуска Uvicorn (будет слушать порт 8000 на хосте)
    command: uvicorn main:app --host 0.0.0.0 --port 8000
