version: '3.8'

services:
  app:
    build: .                       # Собираем образ из вашего Dockerfile
    container_name: fastapi_app

    # Пробрасываем порт 8000 контейнера на порт 8000 хоста
    ports:
      - "8000:8000"

    environment:
      # Подключаемся к MongoDB, запущенному на хосте по адресу docker0 (Linux)
      MONGO_URI: "mongodb://172.17.0.1:27017/"
      DB_NAME:   "namaz_db"

    # Всегда рестартуем при падении
    restart: unless-stopped

    # Запускаем Uvicorn на 0.0.0.0:8000 внутри контейнера
    command: uvicorn main:app --host 0.0.0.0 --port 8000
