# docker-compose.yml
version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app

    # Проброс порта приложения
    ports:
      - "8000:8000"

    # Переменные окружения: приложение подключится к MongoDB на хосте
    environment:
      MONGO_URI: "mongodb://host.docker.internal:27017/"
      DB_NAME: "namaz_db"
      PORT: "8000"

    # Для Linux пробрасываем host.docker.internal → IP-шлюза Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Команда старта Uvicorn
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000

    restart: unless-stopped
