version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app

    # Пробрасываем хостовый порт 8080 → контейнерный 8000
    ports:
      - "8080:8000"

    environment:
      MONGO_URI: "mongodb://host.docker.internal:27017"
      DB_NAME:   "namaz_db"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: always

    # В контейнере Uvicorn по-прежнему слушает 8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
