# docker-compose.yml — FastAPI на порту 8080 + MongoDB на хосте
version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app

    ports:
      - "8080:8080"         # Проброс порта 8080

    environment:
      MONGO_URI: "mongodb://host.docker.internal:27017"
      DB_NAME:   "namaz_db"
      PORT:      "8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: always

    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8080
