# docker-compose.yml
services:
  app:
    build: .
    container_name: fastapi_app

    # берём переменные из .env
    env_file:
      - .env

    # хостовый порт 8080 → контейнерный PORT (8000)
    ports:
      - "8080:${PORT}"

    # чтобы host.docker.internal резолвился в IP хоста (Linux)
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # команда запуска Uvicorn (порт берётся из PORT)
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT}

    restart: always
